### PR TITLE
Improve docs for server-side code snippet

### PR DESCRIPTION
**Pull request by gregjopa**
This PR contains a couple tweaks to the server-side code snippet comments:
- Adds a note to explaining the error handling is dependent on the API strategy
- One line comments shorten up the snippet

Screen Shot 2020-07-29 at 5 06 08 PM

Thanks to @PrestonPHX for these recommendations 😄

### CODE REVIEW

**Comment by mnicpt** [comment]
`serverData` seems too generic.  All data from the server is server data.  It seemed that `orderData` is more specific to the kind of data being returned.

**Comment by PrestonPHX** [comment]
order is a bit too API specific, it might still be a v1/payments execute or DoExpressCheckoutPayment API.  And this generic 'serverData' actually _could_ be any sort of data structure from the server, which is something people are frequently confused about, e.g. https://stackoverflow.com/questions/62817388/paypal-checkout-buttons-client-server-communication 

The even more generic 'data' would be used (and was for createOrder in earlier versions), except this collides with use earlier in the function chain, so with serverData we better disambiguate between the client side data you start off with and what was just returned from the server

**Comment by gregjopa** [comment]
You both make good points 🤔 The hope is to use this variable name to communicate that this payload depends on the server-side implementation. 

Do you have any other suggestions for variable names? What do you think about `orderDataFromServer` or `newOrderFromServer`?

**Comment by mnicpt** [comment]
Are customers complaining that they don't know where the data is coming from?  The only thing I would say regarding naming is that the variable name relates to the API call.  If customers are confused by the variable name, then maybe `orderDataFromServer`.  But I am curious if this is an isolated complaint or widespread because I can't wrap my mind around someone not knowing this is coming from the server.

**Comment by PrestonPHX** [comment]
Yes, there are a nontrivial number of inexperienced developers confused by this code who are unfamiliar with basic client/server design, and serverData helps them understand what is going on in the sample, where the data is coming from, where it's supposed to go, and the arbitrary nature of it (the fact that its structure is completely defined by their server).  orderData is less informative in this respect, and misleading because it doesn't call out that this orderData object can be anything sent back by the server

I don't think the variable should be much longer given that we reference keys multiple times, so I wouldn't go with more than a single camelCase

**Comment by gregjopa** [comment]
We decided to stick with `orderData` for the variable name. PR has been updated.

**Comment by gregjopa** [comment]
@PrestonPHX and @mnicpt thanks for the discussions on this. Naming things can be tricky.

**Comment by mstuart** [comment]
👍

**Pull request merged**
